name: Zmorse CI
on: 
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: Ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Nodejs setup ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Verify Node.js and pnpm versions
        run: |
              node --version
              pnpm --version

      - name: Clear pnpm and build caches
        run: |
              pnpm store prune
              rm -rf .next
              rm -rf build

      - name: Install dependencies
        run: pnpm install
      
      - name: Run ESLint
        run: pnpm run lint

      - name: Build project
        run: pnpm run build
